### ISSUE TITLE
Make sure featurettes represent all aspects of the company

### ISSUE THREAD

**Issue by stubailo** [meteor/meteor.io#8]
- [x] CSE
- [x] Frontend engineer
- [x] Recruiting
- [x] Marketing / Community
- [x] OSS Meteor
- [x] OSS Apollo
- [ ] Product

**Comment by stubailo** [comment]
Probably requires upping it to 8 features, 4x2?

**Comment by daniman** [comment]
Will call this fixed. The featurettes represent all R&D aspects of the company, and I don't think we plan to show gtm/recruiting there for now.
